### ISSUE TITLE
Published dgraph-lamdba container will not run in arm64 docker environment

### ISSUE THREAD

**Issue by matthewmcneely** [dgraph-io/dgraph-lambda#36]
The dgraph ARM lambda e2e tests are failing. The suspected cause is that the existing lambda image is built for amd64 but falls over when running in an ARM environment.

Steps to verify:

1. I spun up a c6g.large ARM instance with Ubuntu and got a dev environment set up there
2. I tried to run my lambda test suite but the stock dgraph/dgraph-lambda image will not launch on my linux arm ec2 instance. This leads me to believe that Docker on amd64 can "virtualize" arm64 images, but Docker arm environments cannot do the inverse. I tried to spin up the lambda image with a `docker run -it <default-lambda-image> /bin/bash`, I get a `/usr/local/bin/docker-entrypoint.sh: exec format error`
3. On the ARM EC2 instance, I built a dgraph/dgraph-lambda:**local** image. Inspecting the image shows it was built for arm64.
4. I used that image for my lambda test suite and everything's working correctly.

I suggest that we use the new multi-arch docker buildx tool to build lambda for both the linux/amd64 and linux/arm64 environments going forward.

Steps (in a cloned dgraph/dgraph-lambda folder):
```
docker login <to docker hub>
docker buildx create --name mybuilder --driver docker-container
docker buildx use mybuilder
docker buildx build -t matthewmcneely/dgraph-lambda:1.4.0 --push --platform=linux/arm64,linux/amd64 .
```

Note: Replace the `matthewmcneely` dockerhub account above with dgraph's.

![image](https://user-images.githubusercontent.com/1376853/200053078-c0ac1830-2541-4b1e-904e-38f70bf0fbeb.png)

This results in both a arm64 and amd64 image to be associated with that tag. When "pulling" in an arm-based docker environment, the correct image is pulled.

**Comment by matthewmcneely** [comment]
Some handy references:

* https://itnext.io/building-multi-cpu-architecture-docker-images-for-arm-and-x86-1-the-basics-2fa97869a99b
* https://itnext.io/building-multi-cpu-architecture-docker-images-for-arm-and-x86-3-building-in-github-action-ci-a382feab5af9

**Comment by joshua-goldstein** [comment]
Closing this issue as it was resolved in the PR's linked above
